version: "3.9"
name: crm_stack

services:
  db:
    image: postgres:16
    container_name: crm_pg
    environment:
      POSTGRES_DB: crm_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/00_dump.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm_bd"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: node:20-alpine
    container_name: crm_backend
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: crm_bd
      JWT_SECRET: secret123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"
    ports:
      - "4000:4000"

  frontend:
    image: node:20-alpine
    container_name: crm_frontend
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"
    ports:
      - "5173:5173"

volumes:
  pgdata:
